//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112120.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Departments = new HashSet<Department>();
            this.Equipments = new HashSet<Equipment>();
        }
    
        public int Id { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string sex { get; set; }
    
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
    }
}
